//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBaseAnalyzer.Tests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBaseAnalyzer.Tests.TestData.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Base_Common_csproj {
            get {
                return ResourceManager.GetString("Base_Common_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup Label=&quot;Globals&quot;&gt;
        ///    &lt;SccProjectName&gt;SAK&lt;/SccProjectName&gt;
        ///    &lt;SccProvider&gt;SAK&lt;/SccProvider&gt;
        ///    &lt;SccAuxPath&gt;SAK&lt;/SccAuxPath&gt;
        ///    &lt;SccLocalPath&gt;SAK&lt;/SccLocalPath&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFramework&gt;net6.0&lt;/TargetFramework&gt;
        ///    &lt;RootNamespace&gt;Ctc.Palplus.Base.Common&lt;/RootNamespace&gt;
        ///    &lt;AssemblyName&gt;Base.Common&lt;/AssemblyName&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///  &lt;ItemGroup&gt;
        ///    &lt;Compile Remove=&quot;bin_int\**&quot; /&gt;
        ///    &lt;Compile Remove=&quot;o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Base_CommonCP_csproj {
            get {
                return ResourceManager.GetString("Base_CommonCP_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.30729&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{331A4352-3C64-4976-84BA-432CB420AC44}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Base_CommonDesktop_csproj {
            get {
                return ResourceManager.GetString("Base_CommonDesktop_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project&gt;
        ///
        ///	
        ///	&lt;Import Project=&quot;..\..\..\..\DesktopApplications\PalPlusDriverSdkBuilder\SDK.CP.Build.props&quot; /&gt;
        ///
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;RootNamespace&gt;Ctc.Palplus.Base.Common&lt;/RootNamespace&gt;
        ///		&lt;Title&gt;Base Common&lt;/Title&gt;
        ///		&lt;ProductName&gt;Base.Common&lt;/ProductName&gt;
        ///		&lt;AssemblyName&gt;$(ProductName)$(AssemblyPostFixName)&lt;/AssemblyName&gt;
        ///		&lt;Description&gt;PALSystem $(ProductName) API Library&lt;/Description&gt;
        ///		&lt;Product&gt;$(ProductName) $(Info)&lt;/Product&gt;
        ///	&lt;/PropertyGroup&gt;
        ///
        ///	&lt;PropertyGroup&gt;
        ///		&lt;DefaultItemExcludes&gt;*.v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Base_CommonDesktop_Net6_csproj {
            get {
                return ResourceManager.GetString("Base_CommonDesktop_Net6_csproj", resourceCulture);
            }
        }
    }
}
